name: Ubuntu * 4.4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R 4.4
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'

      - name: Set R_LIBS_USER
        run: |
          mkdir -p ${{ github.workspace }}/Rlib
          echo "R_LIBS_USER=${{ github.workspace }}/Rlib" >> $GITHUB_ENV

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libfontconfig1-dev \
            libfreetype6-dev \
            libharfbuzz-dev \
            libfribidi-dev \
            libpng-dev \
            libtiff5-dev \
            libjpeg-dev \

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/Rlib
          key: ubuntu-R-4.4-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ubuntu-R-4.4-
            ubuntu-R-

      - name: Install devtools and remotes
        run: Rscript -e "install.packages(c('devtools', 'remotes'), repos = 'https://cran.rstudio.com/')"

      - name: Install package dependencies
        run: Rscript -e "remotes::install_deps(dependencies = TRUE, Ncpus = parallel::detectCores())"

      - name: Install rcmdcheck and testthat
        run: |
          Rscript -e 'install.packages("rcmdcheck", repos = "https://cran.rstudio.com")'
          Rscript -e 'install.packages("testthat", repos = "https://cran.rstudio.com")'

      - name: Run R CMD check
        run: |
          Rscript -e 'rcmdcheck::rcmdcheck(args = c("--no-install-suggests", "--no-manual"), error_on = "error")'
